//! Database entity models and domain types.
//!
//! This module contains SeaORM entity definitions that map to database tables
//! in the PostgreSQL database. The entities are generated by `sea-orm-codegen`
//! and represent the core domain models for authentication and user management.
//!
//! # Architecture
//!
//! The models follow Domain-Driven Design principles:
//! - Each entity represents a database table
//! - Relations define foreign key relationships
//! - ActiveModelBehavior provides lifecycle hooks
//! - Entities are immutable; use ActiveModel for mutations
//!
//! # Database Mapping
//!
//! - **users**: User accounts with authentication credentials
//! - **refresh_tokens**: JWT refresh tokens for token rotation
//! - **email_verifications**: Email verification tokens and status
//! - **o_auth_accounts**: OAuth provider account linkages
//!
//! # Entity Relations
//!
//! ```text
//! Users (1) ──< (N) RefreshTokens
//!       (1) ──< (N) EmailVerifications
//!       (1) ──< (N) OAuthAccounts
//! ```
//!
//! # Examples
//!
//! ```no_run
//! use cobalt_stack::models::prelude::*;
//! use sea_orm::*;
//!
//! # async fn example(db: &DatabaseConnection) -> Result<(), DbErr> {
//! // Query a user with related refresh tokens
//! let user = Users::find_by_id(user_id)
//!     .find_with_related(RefreshTokens)
//!     .all(db)
//!     .await?;
//! # Ok(())
//! # }
//! ```
//!
//! # Code Generation
//!
//! These entities are generated from the database schema using:
//! ```bash
//! sea-orm-cli generate entity \
//!   -u postgres://user:pass@localhost/db \
//!   -o src/models
//! ```

pub mod prelude;

pub mod email_verifications;
pub mod o_auth_accounts;
pub mod refresh_tokens;
pub mod sea_orm_active_enums;
pub mod users;
