/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/admin/stats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get admin statistics */
    get: operations['get_stats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all users with pagination and filtering */
    get: operations['list_users']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user details by ID */
    get: operations['get_user']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/users/{id}/disable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Disable a user account (soft delete) */
    patch: operations['disable_user']
    trace?: never
  }
  '/api/v1/admin/users/{id}/enable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Enable a user account (restore from soft delete) */
    patch: operations['enable_user']
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * POST /api/auth/login - Login with username/password
     * @description Authenticates user and returns access token.
     *     Rate limited to 5 attempts per 15 minutes per IP.
     */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * POST /api/auth/logout - Logout and invalidate tokens
     * @description Revokes refresh token and blacklists access token.
     */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * GET /api/auth/me - Get current user information
     * @description Protected route - requires valid access token.
     */
    get: operations['get_current_user']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * POST /api/auth/refresh - Refresh access token using refresh token
     * @description Rotates refresh token and returns new access token.
     */
    post: operations['refresh_token']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * POST /api/auth/register - Register a new user
     * @description Creates a new user account with username/email/password.
     *     Returns access token on success.
     */
    post: operations['register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/send-verification': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * POST /api/auth/send-verification - Send verification email
     * @description Protected route - requires valid access token.
     */
    post: operations['send_verification_email']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/verify-email': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * POST /api/auth/verify-email - Verify email with token
     * @description Public route - verifies email address using token from email.
     */
    post: operations['verify_email']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health check endpoint
     * @description Returns a simple health status to verify the server is running.
     */
    get: operations['health_check']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Admin statistics */
    AdminStatsResponse: {
      /** Format: int64 */
      admin_users: number
      /** Format: int64 */
      disabled_users: number
      /** Format: int64 */
      total_users: number
      /** Format: int64 */
      verified_users: number
    }
    /** @description User response for admin view (includes all fields) */
    AdminUserResponse: {
      /** Format: date-time */
      created_at: string
      /** Format: date-time */
      disabled_at?: string | null
      email: string
      email_verified: boolean
      /** Format: uuid */
      id: string
      /** Format: date-time */
      last_login_at?: string | null
      role: components['schemas']['UserRole']
      /** Format: date-time */
      updated_at: string
      username: string
    }
    AuthResponse: {
      access_token: string
      /** Format: int64 */
      expires_in: number
      token_type: string
    }
    ErrorResponse: {
      error: string
    }
    HealthResponse: {
      /**
       * @description Health status of the service
       * @example healthy
       */
      status: string
    }
    LoginRequest: {
      /** @example SecurePass123! */
      password: string
      /** @example alice */
      username: string
    }
    /** @description Generic message response */
    MessageResponse: {
      message: string
    }
    RegisterRequest: {
      /** @example alice@example.com */
      email: string
      /** @example SecurePass123! */
      password: string
      /** @example alice */
      username: string
    }
    /** @description Paginated list response */
    UserListResponse: {
      /** Format: int64 */
      page: number
      /** Format: int64 */
      per_page: number
      /** Format: int64 */
      total: number
      /** Format: int64 */
      total_pages: number
      users: components['schemas']['AdminUserResponse'][]
    }
    UserResponse: {
      email: string
      email_verified: boolean
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      id: string
      role: components['schemas']['UserRole']
      username: string
    }
    /**
     * @description User role enum for role-based access control (RBAC).
     *
     *     Defines the authorization level for a user account.
     *     Used in middleware to enforce access control policies.
     *
     *     # Variants
     *
     *     - `User`: Standard user with access to their own resources
     *     - `Admin`: Administrator with elevated privileges
     *
     *     # Database Mapping
     *
     *     Maps to PostgreSQL ENUM `user_role` with values:
     *     - `"user"` → [`UserRole::User`]
     *     - `"admin"` → [`UserRole::Admin`]
     *
     *     # Examples
     *
     *     ```
     *     use cobalt_stack::models::sea_orm_active_enums::UserRole;
     *
     *     let role = UserRole::User;
     *     assert_eq!(serde_json::to_string(&role).unwrap(), "\"user\"");
     *
     *     let admin = UserRole::Admin;
     *     assert_eq!(serde_json::to_string(&admin).unwrap(), "\"admin\"");
     *     ```
     * @enum {string}
     */
    UserRole: 'user' | 'admin'
    VerifyEmailRequest: {
      /** @example abc123def456 */
      token: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_stats: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Admin statistics */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminStatsResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_users: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number
        /** @description Number of items per page */
        per_page?: number
        /** @description Filter by role */
        role?: string | null
        /** @description Filter by email verification status */
        email_verified?: boolean | null
        /** @description Search by username or email */
        search?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of users */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserListResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID (UUID format) */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminUserResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  disable_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID (UUID format) */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User disabled */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  enable_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID (UUID format) */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User enabled */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logged out successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_current_user: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User information */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  refresh_token: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Token refreshed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      /** @description Invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description User registered successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description User already exists */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  send_verification_email: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Verification email sent */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      /** @description Email already verified */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  verify_email: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailRequest']
      }
    }
    responses: {
      /** @description Email verified successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      /** @description Invalid or expired token */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  health_check: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
}
